<?php
// $Id$
/**
 * @file signup_pane_example.module
 * A very simple example signup pane module.
 */

/**
 * Implementation of hook_signup_pane_info().
 *
 * Defines panes available to signup forms.
 * 
 * @return
 *  An associative array of data about signup form panes. 
 *  The key is the pane ID. The value is itself an associative array of the
 *  following form:
 *    - label: A label for the admin UI.
 *    - description: A longer description for the admin UI.
 *    - callback: A callback function to generate the form.
 *  The callback function should have the following signature:
 *   function my_callback(&$signup_form, &$form_state, $node, $signup, $pane_id, $signup_type = 'auth')
 *  where the parameters are:
 *  - $signup_form: Incoming form array, for information only.
 *  - $form_state: Incoming array from the form builder function.
 *  - $node: The fully loaded node object.
 *  - $signup: The fully loaded signup object; or NULL if this is a new signup.
 *  - $pane_id: The id of the pane currently being invoked. This allows a module
 *    to use one callback for several panes.
 *  - $signup_type: The type of signup, which may influence what form is returned:
 *    - 'auth' -- regular authenticated user signup form
 *    - 'anon' -- anonymous user signup form (main form includes required email field).
 *    - 'admin' -- admin form to signup another user (main form includes user selector).
 */
function signup_pane_example_signup_pane_info() {
  return array(
    'example' => array(
      'label' => t('Favourite colour'),
      'description' => t('Should probably be blue.'),
      'callback' => 'signup_pane_example_form',
    ),
  );
}

/**
 * Signup form pane callback.
 *
 * @param &$signup_form
 *   The form array for the whole signup. You should not alter this, but it
 *   contains useful data depending on circumstances.
 * @param &$form_state
 *   Likewise.
 * @param $node
 *   The fully loaded node object.
 * @param $signup
 *   If this is an existing signup, the fully loaded node object. If this is a 
 *   new signup, this is just NULL.
 * @param $pane_id
 *   The pane ID being invoked. This allows a module to implement multiple panes
 *   with one callback.
 * @param $signup_type
 *   Determines what kind of signup to generate a form for. Possible values:
 *    'auth' -- regular authenticated user signup form
 *    'anon' -- anonymous user signup form (includes required email field).
 *    'admin' -- admin form to signup another user (includes user selector).
 * @return
 *   A form API array for insertion into the signup form. 
 */
function signup_pane_example_form(&$signup_form, &$form_state, $node, $signup, $pane_id, $signup_type = 'auth') {
  $form['favorite_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Favourite colour'),
    '#size' => 40, '#maxlength' => 64,
    '#required' => TRUE,
  );
  return $form;
}

/**
 * Implementation of hook_signup_data_alter().
 *
 * If we want to handle our own data storage rather than let signup module do it,
 * we can intercept a signup here before it is saved, extract our data (and
 * unset it in the incoming array), and save it to our own database tables.
 *
 * The advantage of doing this is that we can use it in Views as a field in its
 * own right, which allows sorting and filtering.
 */
//function signup_pane_example_signup_data_alter(&$signup, $form_values) { }


/**
 * Implementation of hook_signup_form_data_display_alter().
 *
 * Alter signup form data prior to displaying signup records in, for example,
 * a node's list of signups.
 *
 * Alternatively, if we are storing data ourselves, we may wish to load it 
 * and insert it into the form_data array.
 *
 * @param $form_data
 *  The user's signup data to alter.
 * @param $nid
 *  The node id for the signup-enabled node.
 * @param $sid
 *  The signup record id. WARNING: NOT the submission sid!
 */
function signup_pane_example_signup_form_data_display_alter(&$form_data, $nid, $sid) {
  if (isset($form_data['example'])) {
    // Change our data array key from the form element key to something nicely readable.
    $form_data['example']['Favourite colour'] = $form_data['example']['favorite_color'];
    unset($form_data['example']['favorite_color']);
  }
}

/**
 * Implementation of hook_signup_cancel().
 *
 * A signup is being cancelled. 
 * If we are storing our own data for this signup, we should delete it here.
 */
//function signup_pane_example_signup_cancel($signup, $node) { }

/**
 * Implementation of hook_nodeapi().
 *
 * A whole signup-enabled node is being deleted.
 * If we are storing our own data, we should delete all of it that relates to 
 * this node.
 */
//function signup_pane_example_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) { }
