<?php
// $Id$
/**
 * @file signup_profile.module
 * Provides integration with profile module.
 *
 * Comments a-plenty as this is also an example of how to use the API.
 * This shows an example of how a signup pane can elect to do its own storage
 * of its signup data rather than letting signup handle storage.
 */

/**
 * Implementation of hook_signup_pane_info().
 *
 * This should return an associative array of data about signup form panes.
 */
function signup_profile_signup_pane_info() {
  // Get the categories. This may return NULL if none are defined yet.
  $categories = _signup_profile_available_categories();
  if (!is_null($categories)) {
    foreach ($categories as $category) {
      // Make a pane for each category.
      $panes['profile_' . $category['name']] = array(
        'label' => 'Profile: ' . $category['name'],
        'description' => t('Collects @category profile fields.', array('@category' => $category['name'])),
        'callback' => 'signup_profile_form',
      );
    }
  }
  
  return $panes;
}

/**
 * Helper function to get profile categories that users have access to.
 *
 * This result is cached as we may need it several times.
 */
function _signup_profile_available_categories() {
  static $available_categories;
  
  if (isset($available_categories)) {
    return $available_categories;
  }
  
  // Get all the categories.
  $categories = profile_categories();
  // Get the number of fields in each category according to access. This will
  // let us determine if a category actually applies.
  $result = db_query("SELECT category, COUNT(*) AS count FROM profile_fields  WHERE visibility <> 4 GROUP BY category", PROFILE_HIDDEN);
  while ($row = db_fetch_array($result)) {
    $categories_count[$row['category']] = $row['count'];
  }
  foreach ($categories as $category) {
    if (isset($categories_count[$category['name']])) {
      $available_categories[] = $category;
    }
  }
  
  return $available_categories;
}

/**
 * Signup form pane callback.
 *
 * @param &$signup_form
 *   The form array for the whole signup. You should not alter this, but it
 *   contains useful data depending on circumstances, such as the signup 
 *   object (in $form['#signup']) when an existing signup is being edited.
 * @param &$form_state
 *   Likewise.
 * @param $node
 *   The fully loaded node object.
 * @param $pane_id
 *   The pane ID being invoked. This allows a module to implement multiple panes
 *   with one callback.
 * @param $signup_type
 *   Determines what kind of signup to generate a form for. Possible values:
 *    'auth' -- regular authenticated user signup form
 *    'anon' -- anonymous user signup form (includes required email field).
 *    'admin' -- admin form to signup another user (includes user selector).
 * @return
 *   A form API array for insertion into the signup form. 
 */
function signup_profile_form(&$signup_form, &$form_state, $node, $pane_id, $signup_type = 'auth') {
  $form = array();
  
  // BIG @TODO: what do we do if this is an anon???
  // maybe a setting to either:
  //  a) create a user account based on the entered anon email
  //  b) just don't show this pane and don't collect data
  //  c) give the user the choice
  
  // Get the real category name from the prefixed pane ID.
  $category = substr($pane_id, 8);
  
  // Call profile.module's implementation of hook_user's form op.
  // This is a smidgen hacky, but safe, as:
  // - $edit is just checked for default values, passing nothing won't hurt. 
  //   @todo: make this bit work for bonus points!
  // - $user is not looked at at all.
  $form = profile_form_profile(array(), NULL, $category, FALSE);
  
  // @TODO: move this up to the caller and pass in $signup, $account.
  // Our data is not in the signup data, so we prepopulate this form
  // with our own default values where applicable.
  if (isset($signup_form['#signup']) && $signup_type != 'anon') {
    // Existing signup: get the account.
    $account = user_load($signup_form['#signup']->uid);
  }
  elseif ($signup_type == 'auth') {
    // An authenticated user is signup themselves up. 
    // Prefill their profile values so they can either leave them or know what 
    // they are changing.
    global $user;
    // Need to do a user_load to get profile fields.
    $account = user_load($user->uid);
  }
  
  if (isset($account)) {
    // Set the form's defaults to the profile values. 
    foreach (element_children($form[$category]) as $key) {
      $form[$category][$key]['#default_value'] = $account->$key;
    }
    $form[$category]['#description'] = t('This information is from your site profile; changes you make here will be saved into it.');
  }
    
  return $form;
}

/**
 * Implementation of hook_signup_data_alter().
 *
 * This allows us to alter the signup data prior to it being saved, do our own
 * saving of profile data, and remove the profile data from the signup so it is
 * not saved in the {signup_log} table's serialized array.
 */
function signup_profile_signup_data_alter(&$signup, $form_values) {
  // BIG @TODO: what do we do if this is an anon???
  
  // Check we have incoming data that concerns us.
  foreach($signup->form_data as $pane_id => $form_data_pane) {
    if (substr($pane_id, 0, 7) == 'profile') {
      $profile_pane_ids[] = $pane_id;
    }
  }
  
  if (isset($profile_pane_ids)) {
    // Get the user account.
    $account = user_load($signup->uid);
    
    foreach ($profile_pane_ids as $pane_id) {
      // Get the real category name from the prefixed pane ID.
      $category_name = substr($pane_id, 8);
      $profile_data = $signup->form_data['profile_' . $category_name][$category_name];
      
      // Again, a bit hackish, but probably safe to call:
      // function profile_save_profile(&$edit, &$user, $category, $register = FALSE)
      // $edit is an array of form element ID => value which we have too.
      // $user we pass the account for the signup.
      profile_save_profile($profile_data, $account, $category_name, FALSE);
      
      // Unset our data from the signup so it's not saved redundantly.
      unset($signup->form_data['profile_' . $category_name]);
    }    
  }
}
